### ISSUE TITLE
Question about custom seq2seqtrainer

### ISSUE THREAD

**Issue by paulc900** [luka-group/Lattice#9]
Hi,
First of all, thank you for the great work!
I'm a newbie in transformers and looking into some tasks like you guys did and reached your paper and code.

I have a quick question about custom seq2seqtrainer (`trainer_seq2seq.py`) that you created in `model` directory.
This might be a stupid question, but...
Is the `prediction_step` in the `trainer_seq2seq.py` the function for training with putting type_ids, row_ids, and col_ids into the model?

I mean, I followed your code line by line, and now I'm trying to put an extra param like `type_ids` as yours in my T5ForConditionalGeneration by using normal `transformers.Trainer`, but gives me an error like below.

`ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (` `type_ids` `in this case) have excessive nesting (inputs type` `list` `where type` `int` `is expected).`

It seems that this error occurs using the general Trainer library, but I want to confirm just in case.

Thanks
Hope you have a happy new year
Paul

**Comment by FeiWang96** [comment]
Hi, thank you for your interest!

This error occurs when inputs are not padded to the same length, because the batch operation assumes that all tensors in the same batch belonging to the same param are of the same length.

Although the implementation could be different when using different version of `huggingface/transformers`, the following steps are essential to add custom params:
* Add custom params in the model ([example](https://github.com/luka-group/Lattice/blob/10560799ded087dd60b9b71bb2c2b5a90f09b850/model/modeling_t5.py#L1513));
* Pad custom params in `tokenizer` ([example](https://github.com/luka-group/Lattice/blob/10560799ded087dd60b9b71bb2c2b5a90f09b850/model/tokenizer.py#L74)).
* Add custom params in `gen_kwargs` in `trainer` ([example](https://github.com/luka-group/Lattice/blob/10560799ded087dd60b9b71bb2c2b5a90f09b850/model/trainer_seq2seq.py#L114));
* If the custom params are used by the decoder, you may also need to add them in `prepare_inputs_for_generation` ([example](https://github.com/tencent-ailab/season/blob/a589bb1f8fb3ec275ed1ecc408b5437db6e4d479/model.py#L1476)).

I'd suggest going through one forward pass to check whether param values are as expected.

Hope it helps.

**Comment by paulc900** [comment]
Thank you for answering my question kindly with the advice and examples!

> This error occurs when inputs are not padded to the same length, because the batch operation assumes that all tensors in the same batch belonging to the same param are of the same length.

Oh I see, the error doesn't occur when I set it as `self.tokenizer(entries['amr'], padding=True, truncation=True, return_offsets_mapping=True)`. However, it pads 1 instead of 0 in `type_ids` when I debug the type_ids before the model goes into `train()`.
Is this why you put custom `_pad` function in the `tokenizer.py`?

> Add custom params in the model ([example](https://github.com/luka-group/Lattice/blob/10560799ded087dd60b9b71bb2c2b5a90f09b850/model/modeling_t5.py#L1513));
> Pad custom params in tokenizer ([example](https://github.com/luka-group/Lattice/blob/10560799ded087dd60b9b71bb2c2b5a90f09b850/model/tokenizer.py#L74)).
> Add custom params in gen_kwargs in trainer ([example](https://github.com/luka-group/Lattice/blob/10560799ded087dd60b9b71bb2c2b5a90f09b850/model/trainer_seq2seq.py#L114));
> If the custom params are used by the decoder, you may also need to add them in prepare_inputs_for_generation ([example](https://github.com/tencent-ailab/season/blob/a589bb1f8fb3ec275ed1ecc408b5437db6e4d479/model.py#L1476)).

Thank you for giving me the advice and examples!
I'll try to follow those steps!

Thank you so much once again for the help ad advice! I really appreciated it!

**Comment by paulc900** [comment]
I come up with one more quick question while I'm training the model with adding custom param.
The loss of the model decreases well during training, but the metric score is low in evaluation..!
Is this mean the model is not training well..? or might the decoder be the problem..?
Do you have any guesses..?

Thank you once again!

Best,
Paul

**Comment by FeiWang96** [comment]
> Is this why you put custom _pad function in the tokenizer.py?

We customize the tokenizer because by default it won't pad custom params.

> The loss of the model decreases well during training, but the metric score is low in evaluation..!

Many reasons may cause this phenomenon, such as distribution shift between the train and eval dataset, inconsistency between the training objective and metric, and also bugs.
